spring:
  application:
    name: backend-kotlin-api-vacancy-request
  task:
    scheduling:
      pool:
        size: 10
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:127.0.0.1}:${DATABASE_PORT:5432}/${DATABASE_NAME:delivery}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}